### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by GOATv2** [Mistercoolertyper/Krampus-SynUI#2]
At the capability too stretch the application.

**Comment by Mistercoolertyper** [comment]
Not sure if I'll do this since idk if it would cause bugs that I can fix very well since this just depends on the old synapse src leak for the ui and that didn't have support for resizing. I'm generally not working on this ui a lot rn since I'm working on making a new and way better one but I'll still probably push bug fixes and stuff to this ui.

**Comment by Mistercoolertyper** [comment]
dont think i'll actually do this since window rezising with webview and monaco can be rlly buggy and never really works correctly and also, synapse didnt have resizing and ig this keeps it more accurate to how syn was(and also i think some stuff will look rlly bad if u could resize it)
