### ISSUE TITLE
Stuck at Initializing Screen

### ISSUE THREAD

**Issue by ActualMasterOogway** [Mistercoolertyper/Krampus-SynUI#3]
![image](https://github.com/Mistercoolertyper/Krampus-SynUI/assets/125769645/b9a29852-979a-434c-9e61-c67180c254ee)
I open Synapse UI WPF.exe and it will be stuck at the Loader Screen

**Comment by Mistercoolertyper** [comment]
loader.live is currently down which means the ui won't be able to connect to the websocket. no custom uis work currently until the loader.live website is back up, I may make a message box to show when it can't connect instead of freezing but ye, until the site is back up u won't be able to use custom uis

**Comment by ActualMasterOogway** [comment]
> loader.live is currently down which means the ui won't be able to connect to the websocket. no custom uis work currently until the loader.live website is back up, I may make a message box to show when it can't connect instead of freezing but ye, until the site is back up u won't be able to use custom uis

Oh didn't know that, thanks!
